import {NextResponse} from 'next/server';
export const dynamic='force-dynamic'; export const revalidate=0;
const ITEMS=['elytra','totem_of_undying','netherite_ingot','end_crystal','respawn_anchor','experience_bottle','enchanted_golden_apple','netherite_block','bone','bone_block','dragon_head','shield','clock','bread','arrow','composter','black_concrete','cartography_table','music_disc_11','music_disc_stal'];
function num(s:string){const x=s.replace(/[$,\s]/g,'').toUpperCase(),m=x.endsWith('K')?1e3:x.endsWith('M')?1e6:x.endsWith('B')?1e9:1;return(parseFloat(x)||0)*m}
function med(a:number[]){const x=[...a].sort((a,b)=>a-b);return x.length?x[Math.floor(x.length/2)]:0}
function title(slug:string){return slug.split('_').map(x=>x[0].toUpperCase()+x.slice(1)).join(' ')}
function text(html:string){return html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&#x27;/g,"'").replace(/&nbsp;/g,' ').replace(/\s+/g,' ')}
async function item(slug:string){const url='https://www.donutstats.net/prices/'+slug;try{const c=new AbortController(),t=setTimeout(()=>c.abort(),6500),r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 (compatible; DonutFlipFinder/3.0)','Accept':'text/html'},cache:'no-store',signal:c.signal});clearTimeout(t);if(!r.ok)throw Error(String(r.status));const s=text(await r.text()),name=title(slug),live=s.match(/Cheapest live[\s\S]*?listings[\s\S]*?(\d+) matching listings[\s\S]*?from \$([\d,.]+[KMB]?) to \$([\d,.]+[KMB]?)/i),sales=s.split(/Recent .*? sales/i)[1]?.split(/More DonutSMP item prices/i)[0]||'',salePrices=[...sales.matchAll(/(?:x(\d+)\s+)?Sold by[^$]*\$([\d,.]+(?:\.\d+)?[KMB]?)/gi)].map(m=>num(m[2])/(+(m[1]||1))).filter(Boolean),buy=live?num(live[2]):0,ask=live?num(live[3]):0,depth=live?+live[1]:0,sell=med(salePrices),current=s.match(/current .*? price .*? is \$([\d,.]+(?:\.\d+)?[KMB]?) per unit/i),market=current?num(current[1]):sell;if(!buy&&!sell&&!market)return null;return{name,buy:buy||market,market:market||sell,sell:sell||market,ask:ask||buy||market,depth,sources:1,sourceNames:['DonutStats'],listings:[],sales:salePrices.slice(0,20),url}}catch{return null}}
export async function GET(){const got=(await Promise.all(ITEMS.map(item))).filter((x):x is NonNullable<typeof x>=>!!x),items=got.sort((a,b)=>a.name.localeCompare(b.name)),rows=items.map(x=>{const profit=x.sell-x.buy,roi=x.buy?profit/x.buy*100:0,confidence=x.sales.length>=5&&x.depth>=5?'High':x.sales.length>=2?'Medium':'Low',score=Math.min(100,Math.round(Math.max(0,Math.min(55,roi*1.5))+Math.min(25,x.depth)+Math.min(20,x.sales.length*2)));return{...x,profit,roi,confidence,score}}).filter(x=>x.buy>0&&x.sell>x.buy&&x.roi>=2).sort((a,b)=>b.score-a.score||b.profit-a.profit),asks=items.filter(x=>x.market>0&&x.ask>x.market*1.15).map(x=>({...x,premium:(x.ask/x.market-1)*100})).sort((a,b)=>b.premium-a.premium);return NextResponse.json({rows,items,asks,updatedAt:new Date().toISOString(),mode:items.length?'donutstats-live':'unavailable',sources:[{name:'DonutStats item pages',ok:items.length>0,observations:items.length}]},{headers:{'Cache-Control':'no-store, max-age=0'}})}
