import {NextResponse} from 'next/server';
export const dynamic='force-dynamic'; export const revalidate=0;
type Obs={name:string;price:number;source:string;freshness:number};
const SOURCES=[{name:'DonutStats Live AH',url:'https://www.donutstats.net/auction',freshness:1},{name:'DonutSMP Stats',url:'https://donutsmpstats.org/items',freshness:.82},{name:'donut.build',url:'https://www.donut.build/auction',freshness:.65}];
function num(raw:string){const s=raw.replace(/[$,\s]/g,'').toUpperCase(),m=s.endsWith('K')?1e3:s.endsWith('M')?1e6:s.endsWith('B')?1e9:1;return(parseFloat(s)||0)*m}
function clean(s:string){return s.replace(/Image:?/gi,'').replace(/\s+/g,' ').trim()} function key(s:string){return clean(s).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()} function median(a:number[]){const x=[...a].sort((a,b)=>a-b);return x.length?x[Math.floor(x.length/2)]:0}
function parse(source:string,html:string,freshness:number):Obs[]{const text=html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&#x27;/g,"'").replace(/&nbsp;/g,' ').replace(/\s+/g,' '),out:Obs[]=[];const patterns=[/Image:?\s*([A-Za-z0-9 '.-]{2,45})\s+(?:by\s+[A-Za-z0-9_.-]+\s+)?\$([\d,.]+(?:\.\d+)?[KMB]?)/gi,/([A-Z][A-Za-z0-9 '.-]{2,45})\s+\$([\d,.]+(?:\.\d+)?[KMB]?)/g];for(const re of patterns){let m;while((m=re.exec(text))!==null){const name=clean(m[1]),price=num(m[2]);if(price>0&&name.length<46&&!/current|min|max|average|price|change|search|sort/i.test(name))out.push({name,price,source,freshness})}}return out}
async function load(s:typeof SOURCES[number]){try{const c=new AbortController(),t=setTimeout(()=>c.abort(),7000),r=await fetch(s.url,{headers:{'User-Agent':'Mozilla/5.0 (compatible; DonutFlipFinder/2.2)'},cache:'no-store',signal:c.signal});clearTimeout(t);if(!r.ok)throw Error(String(r.status));return{name:s.name,url:s.url,ok:true,obs:parse(s.name,await r.text(),s.freshness)}}catch(e:any){return{name:s.name,url:s.url,ok:false,error:e?.message||'unavailable',obs:[] as Obs[]}}}
export async function GET(){const loaded=await Promise.all(SOURCES.map(load)),by=new Map<string,Obs[]>();for(const src of loaded)for(const o of src.obs){const k=key(o.name);if(k)by.set(k,[...(by.get(k)||[]),o])}
const items=[...by.values()].map(obs=>{const prices=obs.map(x=>x.price).sort((a,b)=>a-b),bySrc=new Map<string,Obs[]>();for(const o of obs)bySrc.set(o.source,[...(bySrc.get(o.source)||[]),o]);const sourceMedians=[...bySrc.values()].map(a=>median(a.map(x=>x.price))),center=median(sourceMedians),filtered=obs.filter(x=>center<=0||x.price>=center*.2&&x.price<=center*5).sort((a,b)=>a.price-b.price);if(!filtered.length)return null;const p=filtered.map(x=>x.price),buy=p[0],market=median(p),ask=p[p.length-1],sources=[...new Set(filtered.map(x=>x.source))],name=filtered.sort((a,b)=>b.freshness-a.freshness)[0].name;return{name,buy,market,sell:market*.95,ask,depth:p.length,sources:sources.length,sourceNames:sources,listings:p.slice(0,20)}}).filter((x):x is NonNullable<typeof x>=>!!x).sort((a,b)=>a.name.localeCompare(b.name));
const rows=items.map(x=>{const profit=x.sell-x.buy,roi=x.buy?profit/x.buy*100:0,confidence=x.sources>=3?'High':x.sources>=2?'Medium':'Low',score=Math.min(100,Math.round(Math.min(55,Math.max(0,roi)*1.5)+Math.min(25,x.depth*3)+x.sources*7));return{...x,profit,roi,confidence,score}}).filter(x=>x.profit>0&&x.roi>=2).sort((a,b)=>b.score-a.score||b.profit-a.profit).slice(0,150);
const asks=items.filter(x=>x.ask>x.market*1.15).map(x=>({...x,premium:(x.ask/x.market-1)*100})).sort((a,b)=>b.premium-a.premium).slice(0,150);
return NextResponse.json({rows,items,asks,updatedAt:new Date().toISOString(),mode:'multi-source',sources:loaded.map(x=>({name:x.name,url:x.url,ok:x.ok,observations:x.obs.length,error:'error'in x?x.error:undefined}))},{headers:{'Cache-Control':'no-store, max-age=0'}});}